name: python_all_310
channels:
- conda-forge
- pytorch
- defaults
dependencies:
- python=3.10
- pytorch=1.10.2
- scipy
- numpy
- pandas
- matplotlib
- requests
- pip
- pip:
  - dominate
  - torchvision
  - Pillow
  - visdom
  - seaborn